import type { ParsedDesign } from '@/types';
import type { SemanticDesign } from '@/types/semantic';
import type { ScreenCatalogEntry } from '@/types/map';
import { CONTEXT_FOLDER_NAME } from '@/constants';
import { ASSETS_AND_QA, DESIGN_REFERENCE_LAYOUT, FORBIDDEN_GENERIC_RENDERER } from './design-reference';

export function generateGenericBuildMd(
  semantic: SemanticDesign,
  catalog: ScreenCatalogEntry[],
): string {
  const screenList = catalog.map((entry) => `- \`${entry.slug}\` — ${entry.name}`).join('\n');

  return `# Build Guide — General

> Agent entry point for implementing **${semantic.project.name}**

## Before you start

1. **Create or open** your application repository.
2. Place this export at \`./${CONTEXT_FOLDER_NAME}/\` in that repository.
3. Open \`PROMPT.md\` — confirm the **target stack** (or ask the user once), then paste the kickoff prompt.

Run all phases in order. Do not skip screens.

## Phases

1. \`phases/00-overview.md\` — Stack confirmation + project context
2. \`phases/01-design-system.md\` — Tokens, typography, colors
3. \`phases/02-components.md\` — Shared components
4. \`phases/03-screens.md\` — **Implement every screen** in the chosen stack
5. \`phases/04-navigation.md\` — Wire navigation from prototype links
6. \`phases/05-qa.md\` — Visual QA against \`reference.png\`

## Screens (${catalog.length})

${screenList || '_No screens exported._'}

## Rules

- Read \`AGENTS.md\` before writing code.
- Use \`map.json\` + \`reference.png\` as **design reference** — not a runtime layout format.
- Apply **idiomatic patterns** for the stack you confirm with the user.
- Use \`shared/tokens.json\` and \`shared/components.json\`.

---

Generated by OpenContext v${semantic.project.pluginVersion}.
`;
}

export function generateGenericAgentsMd(semantic: SemanticDesign): string {
  return `# Agent Implementation Rules — General

Export target: **General** (stack-agnostic design context)

${FORBIDDEN_GENERIC_RENDERER}

## Stack confirmation (required)

Before implementing screens:

1. **Inspect the repository** (\`package.json\`, existing folders, config files) for an established stack.
2. If the stack is **unclear**, ask the user **one question only**:

   > "Which stack should I use? (e.g. React (Vite/Next), React Native (Expo), Flutter, SwiftUI, Vue, Svelte)"

3. After the user answers, scaffold (if needed) and implement using that stack's **idiomatic** patterns.
4. Do **not** ask per-screen approval — only this single stack question if needed.

If the user filled in \`Target stack:\` in \`PROMPT.md\`, treat that as confirmed.

## Implementation model

- Read \`screens/{slug}/map.json\` and \`reference.png\` **while implementing** each screen.
- Write **proper UI code** for the confirmed stack — components, styles, and composition.
- Do **not** ship a framework-agnostic JSON layout engine.

${DESIGN_REFERENCE_LAYOUT}

${ASSETS_AND_QA}

## Process

1. Confirm stack (see above).
2. Loop \`catalog/screens.json\` — implement **every** screen autonomously.
3. Follow stack-appropriate folder structure (e.g. \`components/\`, \`pages/\` or \`screens/\`, \`styles/\`).
4. Run \`phases/05-qa.md\` visual checks.

## No React Native assumptions

This export does **not** prescribe React Native structure. If the user chooses RN, re-read a React Native–targeted export or ask them to re-export with the **React Native** target for stack-specific \`AGENTS.md\`.

---

Generated by OpenContext v${semantic.project.pluginVersion}.
`;
}

export function generateGenericPhaseFiles(
  semantic: SemanticDesign,
  design: ParsedDesign,
  catalog: ScreenCatalogEntry[],
): Record<string, string> {
  const screenBullets = catalog
    .map(
      (entry) =>
        `- [ ] **${entry.name}** (\`${entry.slug}\`) — ref: \`screens/${entry.slug}/map.json\` + \`reference.png\``,
    )
    .join('\n');

  return {
    'phases/00-overview.md': `# Phase 00 — Overview (General)

Project: **${semantic.project.name}**
Screens: **${catalog.length}**
Export target: **General**
Figma file: ${design.metadata.figmaFileName}
Figma page: ${design.metadata.figmaPageName}

## Prerequisites

- [ ] Application repository exists or will be scaffolded
- [ ] Design context at \`./${CONTEXT_FOLDER_NAME}/\`
- [ ] **Target stack confirmed** (inspect repo or ask user once — see \`AGENTS.md\`)

Read \`AGENTS.md\`, \`BUILD.md\`, and \`PROMPT.md\` before starting.
`,
    'phases/01-design-system.md': `# Phase 01 — Design System

Implement shared tokens before screens.

## Files

- \`shared/tokens.json\` — colors, typography, spacing
- \`shared/components.json\` — component summaries from Figma

## Tasks

- [ ] Create theme/tokens module from \`shared/tokens.json\` (using the confirmed stack's conventions)
- [ ] Register or import font families from typography tokens
- [ ] Map color tokens to theme variables
`,
    'phases/02-components.md': `# Phase 02 — Components

Build reusable components referenced across screens.

## Source

- \`shared/components.json\` (${semantic.summary.componentCount} components)
- Cross-screen patterns in \`screens/*/map.json\` and \`reference.png\`

## Tasks

- [ ] Identify repeated UI patterns (buttons, cards, inputs, navigation chrome)
- [ ] Extract shared components before screen implementation
- [ ] Use the confirmed stack's component model (e.g. React components, Flutter widgets, SwiftUI views)
`,
    'phases/03-screens.md': `# Phase 03 — Screens (General)

Implement **all** screens in the confirmed stack. Do not use a JSON layout engine.

## Checklist

${screenBullets || '_No screens._'}

## Per screen

1. Open \`screens/{slug}/map.json\` and \`reference.png\` as design reference
2. Implement idiomatic UI for the confirmed stack (components + styles — not raw map replay)
3. Load assets from \`assets/\`
4. Match \`reference.png\` before marking complete

## Forbidden

- Generic \`map.json\` runtime renderers
- Codegen scripts that output identical stub files for every screen
`,
    'phases/04-navigation.md': `# Phase 04 — Navigation

Wire screen-to-screen navigation using the confirmed stack's router.

## Files

- \`navigation/flows.json\` — prototype links (${semantic.navigation.linkCount} links)
- \`catalog/screens.json\` — screen list and routes

## Tasks

- [ ] Create routes/views for every catalog entry
- [ ] Connect prototype triggers from \`navigation/flows.json\`
`,
    'phases/05-qa.md': `# Phase 05 — QA

Visual verification against design references.

## Per screen

1. Render at design frame dimensions (see \`screens/{slug}/meta.json\`)
2. Compare to \`screens/{slug}/reference.png\`
3. Fix layout, typography, and color drift

## Checklist

${screenBullets || '_No screens._'}
`,
  };
}
