import type { ParsedDesign } from '@/types';
import type { SemanticDesign } from '@/types/semantic';
import type { ScreenCatalogEntry } from '@/types/map';
import { CONTEXT_FOLDER_NAME } from '@/constants';
import { DESIGN_REFERENCE_LAYOUT, FORBIDDEN_GENERIC_RENDERER } from './design-reference';

export function generateReactNativeBuildMd(
  semantic: SemanticDesign,
  catalog: ScreenCatalogEntry[],
): string {
  const screenList = catalog.map((entry) => `- \`${entry.slug}\` — ${entry.name}`).join('\n');

  return `# Build Guide — React Native

> Agent entry point for implementing **${semantic.project.name}**

## Before you start

1. **Scaffold** an Expo + TypeScript app (Expo Router recommended) if one does not exist.
2. Place this export at \`./${CONTEXT_FOLDER_NAME}/\` in that repository.
3. Paste the kickoff prompt from \`PROMPT.md\` into your AI agent.

Run all phases in order. Do not skip screens.

## Phases

1. \`phases/00-overview.md\` — Project context and constraints
2. \`phases/01-design-system.md\` — Tokens, typography, fonts
3. \`phases/02-components.md\` — Shared components (BottomTabBar, buttons, etc.)
4. \`phases/03-screens.md\` — **Implement every screen** as typed RN modules
5. \`phases/04-navigation.md\` — Expo Router / React Navigation wiring
6. \`phases/05-qa.md\` — Visual QA against \`reference.png\`

## Screens (${catalog.length})

${screenList || '_No screens exported._'}

## Rules

- Read \`AGENTS.md\` before writing code — it defines folder structure and forbidden patterns.
- Implement **real React Native screens** — not a JSON layout engine.
- Use \`map.json\` + \`reference.png\` as design reference while coding each screen.
- Use \`shared/tokens.json\`, \`shared/components.json\`, and \`navigation-notes.md\`.

---

Generated by OpenContext v${semantic.project.pluginVersion}.
`;
}

export function generateReactNativeAgentsMd(semantic: SemanticDesign): string {
  return `# Agent Implementation Rules — React Native

Export target: **React Native** (Expo + TypeScript)

${FORBIDDEN_GENERIC_RENDERER}

## Implementation model

Build **typed, idiomatic React Native UI** — one proper screen module per catalog entry.

- Read \`screens/{slug}/map.json\` and \`reference.png\` **while implementing** that screen.
- Compose screens from **shared components** (\`src/components/\`) and **screen-local components**.
- Translate design intent into \`View\`, \`Text\`, \`Pressable\`, \`Image\`, \`StyleSheet\` — not raw percentage boxes for every node.

${DESIGN_REFERENCE_LAYOUT}

## Project structure

\`\`\`text
src/
  components/           # shared UI (BottomTabBar, PrimaryButton, ScreenContainer, …)
  theme/                # tokens, typography, spacing (from shared/tokens.json)
  navigation/           # route types, linking helpers
  screens/
    {slug}/             # kebab-case matching catalog slug
      index.tsx         # screen composition (default export)
      styles.ts         # StyleSheet.create only
      components/       # screen-only subcomponents (optional)
      types.ts          # screen-local types (optional)
  app/                  # Expo Router route files (thin re-exports to src/screens/…)
\`\`\`

### Route files (Expo Router)

- Route filenames: **kebab-case** matching catalog slug (\`welcome.tsx\`, \`create-league.tsx\`).
- Each \`src/app/{slug}.tsx\` should **re-export** the screen from \`src/screens/{slug}/index.tsx\` — not inline 200 lines of layout.

Example:

\`\`\`tsx
export { default } from '@/screens/welcome';
\`\`\`

## Naming conventions

| Kind | Convention | Example |
| --- | --- | --- |
| Variables, functions, hooks | camelCase | \`handleSignIn\`, \`useWelcomeScreen\` |
| React components | PascalCase | \`WelcomeHeader\`, \`PrimaryButton\` |
| Screen folders | kebab-case | \`screens/create-league/\` |
| Route files (Expo) | kebab-case | \`app/create-league.tsx\` |
| Style keys | camelCase | \`heroImage\`, \`ctaButton\` |

Do **not** use snake_case or kebab-case for component names.

## TypeScript

- **Strict mode** — no \`any\`.
- Type navigation params (\`RootStackParamList\` or Expo Router typed routes).
- Type component props with explicit interfaces.

## Fonts

- Load every font family listed in \`shared/tokens.json\` (\`typography\`, \`fonts\`).
- Do not substitute system fonts when the design specifies Hellix, Poppins, etc.
- Use \`expo-font\` or \`@expo-google-fonts/*\` as appropriate.

## Safe area

- Maps already exclude the status bar via \`contentArea.top\`.
- Do **not** add \`paddingTop: insets.top\` on top of content positioned from the map.
- Use \`SafeAreaView\` or insets only for edges **not** covered by the design reference.

## Shared components (required)

Before phase 03, extract repeated patterns from multiple screens into \`src/components/\`:

- Bottom tab bar / navigation chrome
- Primary and secondary buttons
- Headers with avatar and location
- Cards and list rows used on 2+ screens

**Never** duplicate the same tab bar implementation in all 27 screen files.

## Process

1. Loop \`catalog/screens.json\` — implement **every** screen without per-screen approval prompts.
2. Follow \`phases/03-screens.md\` for each screen's folder structure.
3. Wire navigation from \`navigation/flows.json\` and \`navigation-notes.md\`.
4. Run \`phases/05-qa.md\` visual checks against each \`reference.png\`.

---

Generated by OpenContext v${semantic.project.pluginVersion}.
`;
}

export function generateReactNativePhaseFiles(
  semantic: SemanticDesign,
  design: ParsedDesign,
  catalog: ScreenCatalogEntry[],
): Record<string, string> {
  const screenBullets = catalog
    .map(
      (entry) =>
        `- [ ] **${entry.name}** (\`${entry.slug}\`) → \`src/screens/${entry.slug}/\` — ref: \`screens/${entry.slug}/reference.png\``,
    )
    .join('\n');

  return {
    'phases/00-overview.md': `# Phase 00 — Overview (React Native)

Project: **${semantic.project.name}**
Screens: **${catalog.length}**
Export target: **React Native (Expo + TypeScript)**
Figma file: ${design.metadata.figmaFileName}
Figma page: ${design.metadata.figmaPageName}

## Prerequisites

- [ ] Expo + TypeScript app scaffolded (Expo Router recommended)
- [ ] Design context at \`./${CONTEXT_FOLDER_NAME}/\`
- [ ] Read \`AGENTS.md\` — especially **Forbidden patterns** and **Project structure**

Do **not** build a generic map renderer. Implement real screens.
`,
    'phases/01-design-system.md': `# Phase 01 — Design System (React Native)

## Files

- \`shared/tokens.json\` — colors, typography, spacing
- \`shared/components.json\` — Figma component summaries

## Tasks

- [ ] Create \`src/theme/tokens.ts\` from \`shared/tokens.json\`
- [ ] Create \`src/theme/typography.ts\` with font family helpers
- [ ] Load all required fonts via \`expo-font\` (see typography tokens)
- [ ] Export spacing and color constants for use in \`styles.ts\` files
`,
    'phases/02-components.md': `# Phase 02 — Components (React Native)

Build **shared** components in \`src/components/\` before implementing screens.

## Source

- \`shared/components.json\` (${semantic.summary.componentCount} components)
- Repeated patterns across \`screens/*/map.json\` and \`reference.png\` files

## Tasks

- [ ] Identify cross-screen patterns (tab bar, headers, buttons, cards)
- [ ] Implement shared components with typed props
- [ ] **Do not** re-implement the tab bar separately in each screen folder

Shared components are **required** — phase 03 depends on them.
`,
    'phases/03-screens.md': `# Phase 03 — Screens (React Native)

Implement **all** screens as typed React Native modules. Do not use a JSON layout engine.

## Checklist

${screenBullets || '_No screens._'}

## Per screen (\`src/screens/{slug}/\`)

1. Create \`index.tsx\` — compose shared + local components to match \`reference.png\`
2. Create \`styles.ts\` — all styles via \`StyleSheet.create\` (camelCase keys)
3. Add \`components/\` only for sections unique to this screen
4. Read \`context/screens/{slug}/map.json\` for spacing, colors, and asset paths **while coding**
5. Copy assets from \`context/assets/\` into the project
6. Create thin route file \`src/app/{slug}.tsx\` that re-exports the screen
7. Compare result to \`context/screens/{slug}/reference.png\` before marking done

## Forbidden

- One-line \`<MapScreen map={...} />\` wrappers
- Codegen scripts that generate identical stub files for every screen
- Absolute-positioning every node from the map instead of composing components
`,
    'phases/04-navigation.md': `# Phase 04 — Navigation (React Native)

## Files

- \`navigation/flows.json\` — prototype links (${semantic.navigation.linkCount} links)
- \`navigation-notes.md\` — React Navigation / Expo Router setup
- \`catalog/screens.json\` — route names and slugs

## Tasks

- [ ] Register all routes (Expo Router file-based or React Navigation stack)
- [ ] Type navigation params
- [ ] Wire \`navigation/flows.json\` triggers to \`router.push\` / \`navigation.navigate\`
- [ ] Use modal presentation for popup screens (see catalog slugs containing \`popup\`)
`,
    'phases/05-qa.md': `# Phase 05 — QA (React Native)

Visual verification against design references.

## Per screen

1. Render on ${catalog[0]?.frame.width ?? 390}×${catalog[0]?.frame.height ?? 844} (or full device width with proportional scaling)
2. Compare to \`context/screens/{slug}/reference.png\`
3. Verify fonts, colors, and shared components match — not just bounding boxes

## Checklist

${screenBullets || '_No screens._'}
`,
  };
}
