import type { ParsedDesign } from '@/types';
import type { SemanticDesign } from '@/types/semantic';
import type { ScreenCatalogEntry, VariantGroupEntry } from '@/types/map';
import { CONTEXT_FOLDER_NAME } from '@/constants';
import { toRouteName } from '@/utils/route-names';

export function generateBuildMd(
  semantic: SemanticDesign,
  catalog: ScreenCatalogEntry[],
): string {
  const screenList = catalog.map((entry) => `- \`${entry.slug}\` — ${entry.name}`).join('\n');

  return `# Build Guide

> Agent entry point for implementing **${semantic.project.name}**

## Before you start

1. **Create your app repo** (or open an existing one).
2. Place this export at \`./${CONTEXT_FOLDER_NAME}/\` in that repository.
3. Paste the kickoff prompt from \`PROMPT.md\` into your AI agent, or follow the phases below directly.

Run all phases in order. Do not skip screens.

## Phases

1. \`phases/00-overview.md\` — Project context and constraints
2. \`phases/01-design-system.md\` — Tokens, typography, colors
3. \`phases/02-components.md\` — Shared components
4. \`phases/03-screens.md\` — **Implement every screen** (loop \`catalog/screens.json\`)
5. \`phases/04-navigation.md\` — Wire navigation from prototype links
6. \`phases/05-qa.md\` — Visual QA against \`reference.png\`

## Screens (${catalog.length})

${screenList || '_No screens exported._'}

## Rules

- Read \`AGENTS.md\` before writing code.
- Implement layout from each \`screens/{slug}/map.json\`.
- Compare finished screens to \`screens/{slug}/reference.png\` before marking done.
- Use \`shared/tokens.json\` and \`shared/components.json\` for design system values.

---

Generated by OpenContext v${semantic.project.pluginVersion}.
`;
}

export function generateAgentsMd(semantic: SemanticDesign): string {
  const target = semantic.exportTarget;

  return `# Agent Implementation Rules

## Layout

1. **Primary source:** \`screens/{slug}/map.json\`
2. Use \`placement.preferred\` first, then fall back to \`absolute\`, \`insets\`, or \`center\`.
3. All percentages are relative to the screen **content area** (below status bar).
4. Ignore nodes with \`role: "statusBar"\` when positioning content.
5. Only render nodes where \`visible: true\` unless implementing a documented variant state.

## Typography

- Text nodes use \`sizing: "intrinsic"\` — do **not** set fixed width/height.
- Use \`text.fontSize\` in **pixels**, not percent.

## Images & assets

- Reference \`asset\` paths relative to the \`context/\` package root.
- Preserve \`style.borderRadius\` and \`style.backgroundColor\` when present.

## Responsiveness

- Target the design frame dimensions in \`screen.frame\`.
- Scale using content-area percentages for a balance of fidelity and responsiveness.
- Use \`placementPixels\` only for QA on the design frame, not as the primary layout API.

## Process

1. Loop \`catalog/screens.json\` — implement **every** screen without being asked one-by-one.
2. Follow \`phases/03-screens.md\` for each screen.
3. Run \`phases/05-qa.md\` visual checks against \`reference.png\`.

## Export target

Platform: **${target}**

${target === 'react-native' ? 'See `navigation/flows.json` and `navigation-notes.md` for React Navigation wiring.' : ''}

---

Generated by OpenContext v${semantic.project.pluginVersion}.
`;
}

export function generatePhaseFiles(
  semantic: SemanticDesign,
  design: ParsedDesign,
  catalog: ScreenCatalogEntry[],
): Record<string, string> {
  const screenBullets = catalog
    .map(
      (entry) =>
        `- [ ] **${entry.name}** (\`${entry.slug}\`) — \`screens/${entry.slug}/map.json\` + \`reference.png\``,
    )
    .join('\n');

  return {
    'phases/00-overview.md': `# Phase 00 — Overview

Project: **${semantic.project.name}**
Screens: **${catalog.length}**
Export target: **${semantic.exportTarget}**
Figma file: ${design.metadata.figmaFileName}
Figma page: ${design.metadata.figmaPageName}

## Prerequisites

- [ ] Application project exists in the repository (scaffold if needed — see \`PROMPT.md\`)
- [ ] Design context is at \`./${CONTEXT_FOLDER_NAME}/\`

Read \`AGENTS.md\`, \`BUILD.md\`, and \`PROMPT.md\` before starting implementation.
`,
    'phases/01-design-system.md': `# Phase 01 — Design System

Implement shared tokens before screens.

## Files

- \`shared/tokens.json\` — colors, typography, spacing
- \`shared/components.json\` — component summaries from Figma

## Tasks

- [ ] Create theme/tokens module from \`shared/tokens.json\`
- [ ] Register font families used in typography tokens
- [ ] Map color tokens to theme variables
`,
    'phases/02-components.md': `# Phase 02 — Components

Build reusable components referenced across screens.

## Source

- \`shared/components.json\` (${semantic.summary.componentCount} components)
- Cross-screen patterns in \`screens/*/map.json\`

## Tasks

- [ ] Identify repeated UI patterns (buttons, cards, inputs)
- [ ] Extract shared components before screen implementation
`,
    'phases/03-screens.md': `# Phase 03 — Screens

Implement **all** screens autonomously. Do not wait for per-screen prompts.

## Checklist

${screenBullets || '_No screens._'}

## Per screen

1. Open \`screens/{slug}/map.json\`
2. Build view tree using \`placement.preferred\`
3. Load assets from paths in the map
4. Match \`reference.png\` before marking complete
`,
    'phases/04-navigation.md': `# Phase 04 — Navigation

Wire screen-to-screen navigation.

## Files

- \`navigation/flows.json\` — prototype links (${semantic.navigation.linkCount} links)
${semantic.exportTarget === 'react-native' ? '- `navigation-notes.md` — React Navigation setup\n' : ''}
## Tasks

- [ ] Create routes from \`catalog/screens.json\`
- [ ] Connect prototype triggers to navigation actions
`,
    'phases/05-qa.md': `# Phase 05 — QA

Visual verification against design references.

## Per screen

1. Render screen at \`screen.frame\` dimensions
2. Compare to \`screens/{slug}/reference.png\`
3. Fix layout drift using \`placementPixels\` as a sanity check

## Checklist

${screenBullets || '_No screens._'}
`,
  };
}

export function buildCatalogEntries(
  screens: Array<{ id: string; name: string; bounds: { width: number; height: number } }>,
  slugByScreenId: Map<string, string>,
): ScreenCatalogEntry[] {
  return screens.map((screen) => {
    const slug = slugByScreenId.get(screen.id) ?? screen.id;
    return {
      id: slug,
      slug,
      name: screen.name,
      figmaId: screen.id,
      route: toRouteName(screen.name),
      paths: {
        map: `screens/${slug}/map.json`,
        reference: `screens/${slug}/reference.png`,
        meta: `screens/${slug}/meta.json`,
      },
      frame: {
        width: Math.round(screen.bounds.width),
        height: Math.round(screen.bounds.height),
      },
    };
  });
}

export function buildVariantsJson(
  variants: Record<string, { canonical: string; canonicalSlug: string; skipped: Array<{ id: string; slug: string; name: string }> }>,
): Record<string, VariantGroupEntry> {
  const result: Record<string, VariantGroupEntry> = {};

  for (const [key, value] of Object.entries(variants)) {
    result[key] = {
      canonical: value.canonical,
      canonicalSlug: value.canonicalSlug,
      skipped: value.skipped,
    };
  }

  return result;
}
