import { EXPORT_FILE_NAMES } from '@/constants';
import { formatHumanDate } from '@/utils';
import type { ExportContext } from './base';
import { BaseExporter } from './base';

/**
 * Generates a human-readable README for the exported context package.
 */
export class ReadmeExporter extends BaseExporter {
  readonly id = 'readme';
  readonly fileName = EXPORT_FILE_NAMES.README;

  export(context: ExportContext) {
    const { design, semantic } = context;
    const exportedDate = formatHumanDate(new Date(design.exportedAt));
    const screenNames = design.screens.map((screen) => screen.name).join(', ');

    const content = `# ${semantic.project.name}

> AI-ready design context exported from Figma

## Export Details

| Field | Value |
| --- | --- |
| **Project** | ${semantic.project.name} |
| **Exported** | ${exportedDate} |
| **Plugin Version** | ${semantic.project.pluginVersion} |
| **Figma File** | ${design.metadata.figmaFileName} |
| **Figma Page** | ${design.metadata.figmaPageName} |

## Summary

This folder contains a normalized representation of your Figma design, prepared for consumption by AI coding assistants such as Claude Code, Cursor, Codex, GitHub Copilot, Gemini, Ollama, and other local or cloud models.

| Metric | Count |
| --- | ---: |
| Screens | ${semantic.summary.screenCount} |
| Components | ${semantic.summary.componentCount} |
| Images | ${semantic.summary.imageCount} |
| Icons | ${semantic.summary.iconCount ?? 0} |
| Exported Assets | ${semantic.summary.exportedAssetCount ?? 0} |
| Text Elements | ${semantic.summary.textElementCount} |
| Total Nodes | ${semantic.summary.nodeCount} |

## Exported Screens

${design.screens.length > 0 ? design.screens.map((screen) => `- ${screen.name}`).join('\n') : '_No screens exported._'}

## Contents

- \`data.json\` — Structured, semantic design data including layout hierarchy, components, typography, colors, spacing, assets, and metadata.
- \`assets/images/\` — Cropped raster exports for image layers and icon PNGs.
- \`assets/icons/\` — Exported SVG vector icons from the design.

## Usage

1. Place this \`context/\` folder in your project repository or share it with your AI coding agent.
2. Reference the files when asking an AI assistant to implement, extend, or analyze the design.
3. Use \`data.json\` as the canonical source of truth for design structure and tokens.
4. Reference files in \`assets/\` when implementing images and icons in code.

## Notes

- This package describes design intent; it does not contain generated application code.
- Screen names included in this export: ${screenNames || 'N/A'}.
- Text nodes include resolved font families, styles, weights, and per-segment typography in \`data.json\`.
- Exported assets are cropped to their Figma layer bounds and written to \`assets/images\` and \`assets/icons\`.
- Future OpenContext versions may add additional files such as \`design.md\` and \`tokens.json\`.

---

Generated by [OpenContext](https://github.com/opencontext) v${semantic.project.pluginVersion}.
`;

    return this.buildFile(content);
  }
}
