import { EXPORT_FILE_NAMES } from '@/constants';
import { formatHumanDate } from '@/utils';
import type { ExportContext } from './base';
import { BaseExporter } from './base';

/**
 * Generates a human-readable README for the exported context package.
 */
export class ReadmeExporter extends BaseExporter {
  readonly id = 'readme';
  readonly fileName = EXPORT_FILE_NAMES.README;

  export(context: ExportContext) {
    const { design, semantic } = context;
    const exportedDate = formatHumanDate(new Date(design.exportedAt));
    const screenNames = design.screens.map((screen) => screen.name).join(', ');
    const platform = semantic.platform ?? {};
    const platformLabel = String(platform.label ?? 'General');
    const navigationLinks = semantic.navigation.links;

    const content = `# ${semantic.project.name}

> AI-ready design context exported from Figma

## Export Details

| Field | Value |
| --- | --- |
| **Project** | ${semantic.project.name} |
| **Export Target** | ${platformLabel} |
| **Exported** | ${exportedDate} |
| **Plugin Version** | ${semantic.project.pluginVersion} |
| **Figma File** | ${design.metadata.figmaFileName} |
| **Figma Page** | ${design.metadata.figmaPageName} |

## Summary

This folder contains a normalized representation of your Figma design, prepared for consumption by AI coding assistants such as Claude Code, Cursor, Codex, GitHub Copilot, Gemini, Ollama, and other local or cloud models.

| Metric | Count |
| --- | ---: |
| Screens | ${semantic.summary.screenCount} |
| Prototype Links | ${semantic.navigation.linkCount} |
| Components | ${semantic.summary.componentCount} |
| Images | ${semantic.summary.imageCount} |
| Icons | ${semantic.summary.iconCount ?? 0} |
| Exported Assets | ${semantic.summary.exportedAssetCount ?? 0} |
| Text Elements | ${semantic.summary.textElementCount} |
| Total Nodes | ${semantic.summary.nodeCount} |

## Exported Screens

${design.screens.length > 0 ? design.screens.map((screen) => `- ${screen.name}`).join('\n') : '_No screens exported._'}

## Screen Navigation

${formatNavigationSection(navigationLinks, semantic.exportTarget)}

## Contents

- \`data.json\` — Structured, semantic design data including layout hierarchy, components, typography, colors, spacing, assets, navigation links, and platform notes.
- \`assets/images/\` — Cropped raster exports for image layers and icon PNGs.
- \`assets/icons/\` — Exported SVG vector icons from the design.
${semantic.exportTarget === 'react-native' ? '- `navigation-notes.md` — React Navigation setup guide with route names and navigate() mappings.' : ''}

${formatPlatformSection(semantic)}

## Usage

1. Place this \`context/\` folder in your project repository or share it with your AI coding agent.
2. Reference the files when asking an AI assistant to implement, extend, or analyze the design.
3. Use \`data.json\` as the canonical source of truth for design structure, tokens, and screen-to-screen links.
4. Reference files in \`assets/\` when implementing images and icons in code.
${semantic.exportTarget === 'react-native' ? '5. Use `navigation-notes.md` and `data.json` → `platform.linkMappings` when wiring React Navigation.' : ''}

## Notes

- This package describes design intent; it does not contain generated application code.
- Screen names included in this export: ${screenNames || 'N/A'}.
- Prototype links from Figma are exported in \`data.json\` under \`navigation.links\`.
- Text nodes include resolved font families, styles, weights, and per-segment typography in \`data.json\`.
- Exported assets are cropped to their Figma layer bounds and written to \`assets/images\` and \`assets/icons\`.
- Future OpenContext versions may add additional export targets such as Flutter and SwiftUI.

---

Generated by [OpenContext](https://github.com/opencontext) v${semantic.project.pluginVersion}.
`;

    return this.buildFile(content);
  }
}

function formatNavigationSection(
  links: Record<string, unknown>[],
  exportTarget: string,
): string {
  if (links.length === 0) {
    return '_No prototype links were found on the exported screens._';
  }

  const lines = links.map((link) => {
    const from = String(link.sourceScreenName ?? 'Unknown');
    const element = String(link.sourceNodeName ?? 'Element');
    const to = link.destinationScreenName ? String(link.destinationScreenName) : 'unknown destination';
    const trigger = String((link.trigger as { type?: string } | undefined)?.type ?? 'ON_CLICK');
    return `- **${from}** · \`${element}\` (${trigger}) → **${to}**`;
  });

  if (exportTarget === 'react-native') {
    lines.push(
      '',
      'See `navigation-notes.md` for React Navigation route names and suggested `navigation.navigate(...)` handlers.',
    );
  }

  return lines.join('\n');
}

function formatPlatformSection(semantic: ExportContext['semantic']): string {
  const platform = semantic.platform;
  if (!platform) {
    return '';
  }

  const notes = (platform.implementationNotes as string[] | undefined) ?? [];
  if (notes.length === 0) {
    return '';
  }

  return `## Platform Notes (${String(platform.label ?? semantic.exportTarget)})

${notes.map((note) => `- ${note}`).join('\n')}
`;
}
