import type { ExportTargetId } from '@/constants/export-targets';
import { getExportTargetDefinition } from '@/constants/export-targets';
import { CONTEXT_FOLDER_NAME } from '@/constants';

export interface StarterPromptInput {
  projectName: string;
  exportTarget: ExportTargetId;
  screenCount: number;
}

function getScaffoldInstructions(exportTarget: ExportTargetId): string {
  switch (exportTarget) {
    case 'react-native':
      return 'Scaffold a React Native app (Expo or React Native CLI) in this repository if one does not exist yet. Install React Navigation and any dependencies noted in `context/navigation-notes.md`.';
    case 'flutter':
      return 'Scaffold a Flutter app in this repository if one does not exist yet.';
    case 'swiftui':
      return 'Scaffold an Xcode SwiftUI iOS app in this repository if one does not exist yet.';
    default:
      return 'Scaffold an application project in this repository if one does not exist yet (use a stack appropriate for this design — web, mobile, or full-stack).';
  }
}

/**
 * Ready-to-paste kickoff prompt for AI coding agents.
 * Assumes the exported package lives at ./context in the target repo.
 */
export function generateStarterPrompt(input: StarterPromptInput): string {
  const target = getExportTargetDefinition(input.exportTarget);
  const scaffold = getScaffoldInstructions(input.exportTarget);
  const contextPath = `./${CONTEXT_FOLDER_NAME}`;

  return `I exported Figma design context for **${input.projectName}** into \`${contextPath}/\` in this repository.

**Before you implement any screens:**
1. ${scaffold}
2. Confirm the OpenContext export is present at \`${contextPath}/\` (it should contain \`BUILD.md\`, \`catalog/screens.json\`, and \`screens/\`).

**Then build the full app autonomously — do not ask me screen-by-screen:**
1. Read \`${contextPath}/BUILD.md\` and \`${contextPath}/AGENTS.md\`
2. Run every phase in \`${contextPath}/phases/\` in order (00 → 05)
3. Implement **all ${input.screenCount} screens** from \`${contextPath}/catalog/screens.json\`
4. Use \`${contextPath}/screens/{slug}/map.json\` for layout (percentages are relative to the content area below the status bar)
5. Match each screen to \`${contextPath}/screens/{slug}/reference.png\` before marking it done
6. Copy assets from \`${contextPath}/assets/\` into the project as needed

Export target: **${target.label}**
Work through the entire BUILD.md checklist without stopping for per-screen approval.`;
}

export function generatePromptMd(input: StarterPromptInput): string {
  const prompt = generateStarterPrompt(input);

  return `# Agent Kickoff Prompt

Copy the block below into Cursor, Claude Code, Codex, or your AI coding agent **after** placing this folder at \`./context\` in your project repository.

## Prerequisites

1. Create or open your application repository.
2. Copy this entire \`context/\` folder to \`./context\` at the repository root.
3. Paste the prompt below into your agent.

---

## Prompt (copy from here)

${prompt}

---

## What happens next

The agent should scaffold the project (if needed), then follow \`BUILD.md\` through all phases without asking you to approve each screen individually.

Generated by OpenContext.
`;
}
